#14 Allow generic token_options to be passed via $config[]
softonic/guzzle-oauth2-middleware pull request #15
Opened 2020-01-06 20:37 UTC by jonathan-graf

This enhancement will allow for other token options to be passed through the middleware for compatibility with OAuth2 compatible frameworks that have some "extra" requirements.

2020-01-07 15:07 UTC, akira28 commented
Do you mind adding a test covering this addition? Thank you very much for your contribution!

2020-01-07 15:16 UTC, joskfg commented
In addition to the test, It would be good to add some documentation in the usage part of the README.md

Thanks!

2020-01-07 21:14 UTC, rccrdpccl requested changes
Thanks for the improvement! This looks good, just a few minor changes and it'll get merged.

2020-01-07 21:14 UTC, rccrdpccl commented on src/AddAuthorizationHeader.php
> +            $token_options = $this->config['token_options'];
Please use camelCase for variable names

2020-01-07 21:17 UTC, jonathan-graf commented
> Do you mind adding a test covering this addition? Thank you very much for your contribution!

Not a problem!

2020-01-10 18:21 UTC, rccrdpccl reviewed
What happens when we both declare scope in root config and in `token_options`? Could you please explicit what happens covering this case in the tests? IMO the behaviour is correct, but it is a bit of a quirk to keep backward compatibility, so it would be nice to add a test for it. With this small change is good to merge IMO

2020-01-10 19:44 UTC, jonathan-graf commented
What what you like the intended result to be?  Should we throw an exception
and force scope to only be in root config?

On Fri, Jan 10, 2020 at 7:21 PM Riccardo Piccoli <notifications@github.com>
wrote:

> *@rccrdpccl* commented on this pull request.
>
> What happens when we both declare scope in root config and in
> token_options? Could you please explicit what happens covering this case
> in the tests? IMO the behaviour is correct, but it is a bit of a quirk to
> keep backward compatibility, so it would be nice to add a test for it. With
> this small change is good to merge IMO
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/softonic/guzzle-oauth2-middleware/pull/15?email_source=notifications&email_token=AAPSMMJ65IZWQNQBZOY6T7TQ5C4BFA5CNFSM4KDKME42YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCRMGXPA#pullrequestreview-341339068>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPSMMOSEKUKNZ46R6DZAKTQ5C4BFANCNFSM4KDKME4Q>
> .
>

2020-01-10 20:14 UTC, rccrdpccl commented
I think current behaviour it's good: if it's defined in root config, it works. If it's set in `token_options` it also works. If it's set in both, the new `token_options` it's used. This way the library it's backward compatible (current clients won't break). In case it's declared twice it's a weird scenario, that's why I think it should be explicitly tested.

2020-01-10 20:39 UTC, jonathan-graf commented
Sounds good.  Thanks for clearing that up for me.  I’ll know which
assertions to code very clearly now.

On Fri, Jan 10, 2020 at 9:14 PM Riccardo Piccoli <notifications@github.com>
wrote:

> I think current behaviour it's good: if it's defined in root config, it
> works. If it's set in token_options it also works. If it's set in both,
> the new token_options it's used. This way the library it's backward
> compatible (current clients won't break). In case it's declared twice it's
> a weird scenario, that's why I think it should be explicitly tested.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/softonic/guzzle-oauth2-middleware/pull/15?email_source=notifications&email_token=AAPSMMPA7R72B5HEGFAJYQTQ5DJLTA5CNFSM4KDKME42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIVCVVA#issuecomment-573188820>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPSMMMDLSSUQCWAOX4X2DDQ5DJLTANCNFSM4KDKME4Q>
> .
>

2020-01-23 14:25 UTC, rccrdpccl approved these changes

2020-01-23 14:34 UTC, joskfg approved these changes

2020-01-23 14:35 UTC, akira28 approved these changes

2020-01-23 14:35 UTC, merged